"""Minor cleanup - syncing schema
with latest version of models.

Revision ID: 423a0156bbac
Revises: 1e27c434bb14
Create Date: 2016-03-16 14:56:30.405336

"""

# revision identifiers, used by Alembic.
revision = '423a0156bbac'
down_revision = '1e27c434bb14'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('billing_period', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'billing_period')
    ### end Alembic commands ###
